SAMPLE_PRODUCTS = [
    {"description": "Apple iPhone 15 128GB smartphone", "category": "Electronics", "price": 799.00},
    {"description": "Apple iPhone 15 Pro 256GB smartphone", "category": "Electronics", "price": 1099.00},
    {"description": "Samsung Galaxy S24 128GB Android smartphone", "category": "Electronics", "price": 799.00},
    {"description": "Google Pixel 8 128GB Android smartphone", "category": "Electronics", "price": 699.00},
    {"description": "Apple AirPods Pro wireless noise cancelling earbuds", "category": "Electronics", "price": 249.00},
    {"description": "Sony WH-1000XM5 wireless noise cancelling headphones", "category": "Electronics", "price": 399.00},
    {"description": "JBL portable Bluetooth speaker waterproof", "category": "Electronics", "price": 129.00},
    {"description": "Logitech wireless computer mouse", "category": "Office_Products", "price": 39.00},
    {"description": "Logitech mechanical gaming keyboard RGB", "category": "Office_Products", "price": 119.00},
    {"description": "Dell 24 inch 1080p computer monitor", "category": "Electronics", "price": 159.00},
    {"description": "LG 27 inch 4K computer monitor", "category": "Electronics", "price": 349.00},
    {"description": "Apple MacBook Air 13 inch laptop 256GB", "category": "Electronics", "price": 999.00},
    {"description": "Lenovo IdeaPad 15 inch laptop 512GB SSD", "category": "Electronics", "price": 649.00},
    {"description": "Shure MV7 USB and XLR podcast microphone", "category": "Musical_Instruments", "price": 249.00},
    {"description": "HyperX QuadCast USB condenser microphone", "category": "Musical_Instruments", "price": 139.00},
    {"description": "Fender beginner electric guitar", "category": "Musical_Instruments", "price": 229.00},
    {"description": "Cordless 20V power drill with battery and charger", "category": "Tools_and_Home_Improvement", "price": 99.00},
    {"description": "Cordless circular saw power tool", "category": "Tools_and_Home_Improvement", "price": 149.00},
    {"description": "Robot vacuum cleaner with smart mapping", "category": "Appliances", "price": 299.00},
    {"description": "Air fryer 6 quart digital kitchen appliance", "category": "Appliances", "price": 89.00},
    {"description": "Espresso coffee machine with milk frother", "category": "Appliances", "price": 199.00},
    {"description": "LEGO building set for children", "category": "Toys_and_Games", "price": 59.00},
    {"description": "Remote control off-road toy car", "category": "Toys_and_Games", "price": 49.00},
    {"description": "Car dash camera 4K with night vision", "category": "Automotive", "price": 129.00},
    {"description": "Portable car tire inflator air compressor", "category": "Automotive", "price": 59.00},
]
